plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  instance-state-name: running
  tag:Name: "proji-*"

hostnames:
  - instance-id

compose:
  ansible_connection: aws_ssm
  ansible_user: ubuntu