- name: Testar conexão via SSM
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping via SSM
      ansible.builtin.ping:

    - name: Mostrar ID da instância
      ansible.builtin.debug:
        msg: "Conectado à instância {{ inventory_hostname }}"