name: Ansible CI/CD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: ansible

jobs:
  ansible:
    name: Ansible Configuration (SSM)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::340705986117:role/GitHubRunnerAnsibleRole
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Install Ansible and AWS collection
        run: |
          sudo apt update
          sudo apt install -y ansible
          ansible-galaxy collection install amazon.aws

      - name: Wait for EC2 + SSM readiness
        run: sleep 90

      - name: Validate inventory
        run: ansible-inventory -i inventory/aws_ec2.yml --graph

      - name: Run Ansible Playbook via SSM
        run: ansible-playbook -i inventory/aws_ec2.yml playbook.yml -vv