name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Ação do Terraform"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: terraform/environments/prod

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: ${{ inputs.action != 'destroy' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::340705986117:role/GitHubRunnerTerraformRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config=../../global/backend/backend.hcl

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan.tfout

      - name: Export Terraform Outputs
        run: terraform output -json > outputs.json

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: |
            terraform/environments/prod/tfplan.tfout
            terraform/environments/prod/outputs.json

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest
    if: ${{ inputs.action == 'apply' }}
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform/environments/prod

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::340705986117:role/GitHubRunnerTerraformRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config=../../global/backend/backend.hcl

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.tfout

      - name: Trigger Ansible Pipeline
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "ansible.yml",
              ref: "main"
            })

  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: ${{ inputs.action == 'destroy' }}
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::340705986117:role/GitHubRunnerTerraformRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config=../../global/backend/backend.hcl

      - name: Terraform Destroy
        run: terraform destroy -auto-approve